---
name: Devel-LineName
version: 0.03
author:
  - 'Nick Cleaton <nick@cleaton.net>'
abstract: give names to source code lines
license: perl
build_requires:
  Test::More: 0
requires:
  Carp: 0
  perl: 5.006001
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  Devel::LineName:
    file: lib/Devel/LineName.pm
    version: 0.03
resources:
  license: http://dev.perl.org/licenses/
